export const genres = [
    "Action",
    "Adventure",
    "Anime Series International TV Shows",
    "British TV Shows Docuseries International TV Shows",
    "Children",
    "Comedies",
    "Comedies Dramas International Movies",
    "Comedies International Movies",
    "Comedies Romantic Movies",
    "Crime TV Shows Docuseries",
    "Documentaries",
    "Documentaries International Movies",
    "Docuseries",
    "Dramas",
    "Dramas International Movies",
    "Dramas Romantic Movies",
    "Family Movies",
    "Fantasy",
    "Horror Movies",
    "International Movies Thrillers",
    "International TV Shows Romantic TV Shows TV Dramas",
    "Kids' TV",
    "Language TV Shows",
    "Musicals",
    "Nature TV",
    "Reality TV",
    "Spirituality",
    "TV Action",
    "TV Comedies",
    "TV Dramas",
    "Talk Shows TV Comedies",
    "Thrillers"
];


export const genreKeyMapValues = [
    "Action",
    "Adventure",
    "Anime_Series_International_TV_Shows",
    "British_TV_Shows_Docuseries_International_TV_Shows",
    "Children",
    "Comedies",
    "Comedies_Dramas_International_Movies",
    "Comedies_International_Movies",
    "Comedies_Romantic_Movies",
    "Crime_TV_Shows_Docuseries",
    "Documentaries",
    "Documentaries_International_Movies",
    "Docuseries",
    "Dramas",
    "Dramas_International_Movies",
    "Dramas_Romantic_Movies",
    "Family_Movies",
    "Fantasy",
    "Horror_Movies",
    "International_Movies_Thrillers",
    "International_TV_Shows_Romantic_TV_Shows_TV_Dramas",
    "Kids'_TV",
    "Language_TV_Shows",
    "Musicals",
    "Nature_TV",
    "Reality_TV",
    "Spirituality",
    "TV_Action",
    "TV_Comedies",
    "TV_Dramas",
    "Talk_Shows_TV_Comedies",
    "Thrillers"
];